cookie:
  expiry_days: 15
  key: cookie_signature_key
  name: cookie_name
credentials:
  usernames:
      georgei:
        email: georgeiancu749@yahoo.com
        name: George Iancu
        password: $2b$12$jW7RB.Ho2MsDnpQ4Sk05iezlUw.WYcRFkruO8YNThqEnWVuhvVodq